//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_thue_bao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIENTHOAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIENTHOAI()
        {
            this.THUEBAOs = new HashSet<THUEBAO>();
        }
    
        public string SoDienThoai { get; set; }
        public Nullable<int> LoaiThueBao { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual LOAITHUEBAO LOAITHUEBAO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUEBAO> THUEBAOs { get; set; }
    }
}
