//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_thue_bao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASAU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRASAU()
        {
            this.THUEBAOs = new HashSet<THUEBAO>();
        }
    
        public int IdTraSau { get; set; }
        public string SoDienThoai { get; set; }
        public string TenKhachHang { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<float> GiaTienTraSau { get; set; }
        public Nullable<float> TienNo { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<float> TongTienTra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUEBAO> THUEBAOs { get; set; }
    }
}
